#!/bin/bash

VERSION="$1"
CMD="$2"

if [ "$CMD" = "test" ]; then

    echo "Creating test release..."
    uv sync
    uv version "$VERSION"

    echo "Compiling release..."
    cd $HOME/bespokebpv7
    rm dist/*.whl
    uv build --wheel

    echo "Test Release Created"

elif [ "$CMD" = "prep" ]; then
    echo "Prepping for release..."
    git checkout -b "release-prep-$VERSION"
    python release_scripts/mk_release.py "$VERSION"

    echo "Update CHANGELOG"

elif [ "$CMD" = "release" ]; then
    echo "Trigger release.."
    git tag -f -a "v$VERSION" -m "Release version $VERSION"
    git push origin --tags

else
    echo "Unknown command"

fi
