[project]
name = "bespokebpv7"
version = "0.3.0"
description = "Generate whatever format of BPv7 bundles"
readme = "README.md"
requires-python = ">=3.10.19"
dependencies = [
    "attrs>=25.4.0",
    "cattrs>=25.3.0",
    "cbor2<=5.7.1",
    "dpkt>=1.9.8",
    "fastcrc>=0.3.5",
]

[dependency-groups]
dev = [
    "bandit>=1.9.2",
    "coverage>=7.13.1",
    "hypothesis>=6.150.2",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "tox>=4.34.1",
    "tox-uv>=1.29.0",
]

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN002", "ANN003", "D203", "D205", "D211", "D212", "D213", "D400", "D415", "COM812", "S101"]

[tool.ruff.lint.per-file-ignores]
"main.py" = ["T201", "ERA001"]
"examples/*" = ["INP001", "T201", "FBT001", "FBT002", "S404", "S603"]
"tests/*" = ["INP001"]

[tool.coverage.run]
branch = true
parallel = true
source = ["bespokebpv7"]

[tool.coverage.paths]
source = [
    "src/bespokebpv7",
    "*/site-packages/bespokebpv7",
    "*/bespokebpv7",
]

[tool.coverage.report]
fail_under = 95
show_missing = true
skip_covered = true

[tool.tox]
requires = ["tox>=4.34.1", "tox-uv>=1.29.0"]
env_list = ["clean", "3.10", "3.11", "3.12", "3.13", "3.14", "type", "lint", "coverage"]
isolated_build = true

[tool.tox.env.clean]
description = "Erase previous coverage data"
deps = ["coverage[toml]"]
skip_install = true
allowlist_externals = ["coverage"]
commands = [["coverage", "erase"]]

[tool.tox.env.coverage]
description = "Report coverage over all test runs."
deps = ["coverage[toml]"]
skip_install = true
depends = ["3.10", "3.11", "3.12", "3.13", "3.14"]
allowlist_externals = ["coverage"]
commands = [
    ["coverage", "combine"],
    ["coverage", "report"],
    ["coverage", "html"]
]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
dependency_groups = ["dev"]
commands = [
    ["coverage", "run", "-m", "pytest"]
]

[tool.tox.env.type]
description = "Run type check on code base"
dependency_groups = ["dev"]
commands = [["mypy", "src/bespokebpv7"]]

[tool.tox.env.lint]
description = "Run Ruff"
dependency_groups = ["dev"]
commands = [
    ["ruff", "check", "--fix", "src/bespokebpv7"],
    ["ruff", "format", "src/bespokebpv7"]
]
