[project]
name = "bespokebpv7"
version = "0.1.0"
description = "Generate whatever format of BPv7 bundles"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "attrs>=25.4.0",
    "cattrs>=25.3.0",
    "cbor2>=5.8.0",
    "dpkt>=1.9.8",
    "fastcrc>=0.3.5",
]

[dependency-groups]
dev = [
    "bandit>=1.9.2",
    "coverage>=7.13.1",
    "hypothesis>=6.150.2",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]
